# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/debug_nbdev/',
                'doc_host': 'https://{user}.github.io',
                'git_url': 'https://github.com/{user}/debug_nbdev/',
                'lib_path': 'debug_nbdev'},
  'syms': {'debug_nbdev.core': {'debug_nbdev.core.foo': ('core.html#foo', 'debug_nbdev/core.py')}, 'debug_nbdev.more': {}}}
